Add options encap-flood and description to template_bd
CiscoDevNet/ansible-mso pull request #198
Opened 2021-05-27 13:58 UTC by shrsr

2021-06-03 15:27 UTC, anvitha-jain approved these changes
LGTM

2021-06-21 19:23 UTC, lhercot requested changes

2021-06-21 19:23 UTC, lhercot commented on tests/integration/targets/mso_schema_template_bd/tasks/main.yml
> -    - cm_query_all_bds.current | length == cm_query_all_bds.current | length == 3
Why did we remove this check?

2021-06-21 19:23 UTC, lhercot commented on tests/integration/targets/mso_schema_template_bd/tasks/main.yml
> -    - query_bd_new_subnet_options.current.subnets[2].virtual == true
Why did we remove and changed most of those?

2021-06-22 16:38 UTC, lhercot approved these changes
LGTM

2021-06-22 16:38 UTC, merged