[mso_schema_template_anp_epg] Added description and QoS level parameter to ANP EPG. Fixes issue #195
CiscoDevNet/ansible-mso pull request #208
Opened 2021-06-30 04:13 UTC by anvitha-jain

fixes #195

2021-06-30 04:15 UTC, anvitha-jain reviewed
Cloud properties are VRF and selector
Service properties cannot be evaluated as it needs both enableVersionCheck=true & validate=true

2021-06-30 23:03 UTC, lhercot requested changes

2021-06-30 23:03 UTC, lhercot commented on plugins/modules/mso_schema_template_anp_epg.py
> +    service_path = '/templates/{0}/anps/{1}/epgs/{2}/cloudServiceEpgConfig'.format(template, anp, epg)
You could probably do:
service_path = '{0}/cloudServiceEpgConfig'.format(epg_path)

2021-06-30 23:03 UTC, lhercot commented on plugins/modules/mso_schema_template_anp_epg.py
> +    cloudServiceEpgConfig = {}
lower case and underscore for variable name

2021-06-30 23:03 UTC, lhercot commented on plugins/modules/mso_schema_template_anp_epg.py
> +                cloudServiceEpgConfig.update(dict(deploymentType=deployment_type, serviceType=service_type, accessType=access_type))
Use a dictionnary to map deployment_type and access_type from lowercase value to correct API value.

2021-06-30 23:03 UTC, lhercot commented on tests/integration/targets/mso_schema_template_anp_epg/tasks/main.yml
> +#     state: present
We don't need the tenant?

2021-07-06 17:11 UTC, anvitha-jain commented on tests/integration/targets/mso_schema_template_anp_epg/tasks/main.yml
> +#     state: present
we do.

2021-07-07 16:02 UTC, shrsr commented on plugins/modules/mso_schema_template_anp_epg.py
> +    - The access_type parameter indicates how the service will be accessed.
This parameter indicates how the service will be accessed.

2021-07-07 16:03 UTC, shrsr commented on plugins/modules/mso_schema_template_anp_epg.py
> +    - This parameter is available only when epg_type is service.
It is only available when epg_type is service.

2021-07-07 16:05 UTC, shrsr commented on plugins/modules/mso_schema_template_anp_epg.py
> +    - Quality of Service (QoS) feature allows you to classify the network traffic in your fabric
This feature allows you to classify the network traffic in the fabric

2021-07-07 16:07 UTC, shrsr commented on plugins/modules/mso_schema_template_anp_epg.py
> +    -  and then to prioritize and police the traffic flow to help avoid congestion in your network.
It helps prioritize and police the traffic flow to avoid congestion in the network.

2021-07-12 22:49 UTC, lhercot requested changes

2021-07-12 22:49 UTC, lhercot commented on plugins/modules/mso_schema_template_anp_epg.py
> +    - The service_type parmeter refers to the type of cloud services.
parameter

2021-07-12 22:49 UTC, lhercot commented on plugins/modules/mso_schema_template_anp_epg.py
> +    - Quality of Service (QoS) allows you to classify the network traffic in the fabric
Missing "." at the end of the sentence.

2021-07-13 02:39 UTC, shrsr commented
LGTM

2021-07-13 06:06 UTC, lhercot approved these changes
LGTM

2021-07-13 06:13 UTC, merged