Service graph contract interface
CiscoDevNet/ansible-mso pull request #281
Opened 2022-08-04 23:06 UTC by xinyuezhao

create contract service graph at site level

resolve #275

2022-10-25 04:34 UTC, lhercot commented
@xinyuezhao Can you fix galaxy-importer and sanity issues?

2023-01-23 19:16 UTC, anvitha-jain approved these changes
LGTM

2024-01-10 03:04 UTC, lhercot requested changes

2024-03-01 17:37 UTC, lhercot commented
Closing this PR as #402  is superseeding and include the same changes.

2024-03-01 17:37 UTC, closed without merging