[ignore] add fqcn to all tasks in testcases
CiscoDevNet/ansible-mso pull request #393
Opened 2023-11-29 10:00 UTC by akinross

fixes #387

2023-11-29 18:25 UTC, gmicol approved these changes
LGTM

2023-12-05 04:43 UTC, anvitha-jain approved these changes

2023-12-20 16:44 UTC, lhercot requested changes

2023-12-20 16:44 UTC, lhercot commented on tests/integration/targets/mso_schema_site_l3out/tasks/main.yml
> +  ansible.builtin.ansible.builtin.fail:
```suggestion
  ansible.builtin.fail:
```

2023-12-20 20:20 UTC, lhercot approved these changes
LGTM

2023-12-20 20:20 UTC, merged