Fixed the useg_subnet logic in the mso_schema_template_anp_epg_useg_attribute.py module
CiscoDevNet/ansible-mso pull request #397
Opened 2024-01-11 14:40 UTC by sajagana

Note:

Fixed the useg_subnet logic and added additional validation tasks

2024-01-11 15:34 UTC, shrsr requested changes

2024-01-11 15:34 UTC, shrsr commented on plugins/modules/mso_schema_template_anp_epg_useg_attribute.py
> +                    mso.fail_json(msg="The value should be empty string or 0.0.0.0, when the useg_subnet is true.")
mso.fail_json(msg="The value of uSeg should be an empty string or 0.0.0.0, when the useg_subnet is set to true.")

2024-01-11 15:34 UTC, shrsr commented on tests/integration/targets/mso_schema_template_anp_epg_useg_attribute/tasks/main.yml
> +      - ans_test_uSeg_1_nt1.msg == "The value should be empty string or 0.0.0.0, when the useg_subnet is true."
- ans_test_uSeg_1_nt1.msg == "The value of uSeg should be an empty string or 0.0.0.0, when the useg_subnet is set to true."

2024-01-11 23:27 UTC, samiib submitted a review, later dismissed
Just considering @shrsr's suggestion makes sense, everything else LGTM. 😄

2024-01-12 12:33 UTC, akinross approved these changes
LGTM

2024-01-17 00:41 UTC, lhercot approved these changes
LGTM

2024-01-17 00:41 UTC, merged