[minor_change] Add support for required attributes introduced in ndo4…
CiscoDevNet/ansible-mso pull request #403
Opened 2024-01-23 11:39 UTC by akinross

….2 for mso_schema_site_anp_epg_domain

fixes #377

2024-01-24 21:32 UTC, samiib submitted a review, later dismissed
LGTM

2024-01-29 18:23 UTC, shrsr approved these changes
LGTM

2024-02-15 18:43 UTC, gmicol submitted a review, later dismissed
LGTM

2024-02-27 22:12 UTC, lhercot requested changes

2024-02-27 22:12 UTC, lhercot commented on plugins/modules/mso_schema_site_anp_epg_domain.py
> +    - Which delimiter to use with this domain association. This attribute can only be used with vmmDomain domain association.
```suggestion
    - Which delimiter to use with this domain association. This attribute can only be used with VMM domain associations.
```

2024-02-27 22:12 UTC, lhercot commented on plugins/modules/mso_schema_site_anp_epg_domain.py
> +    - Which binding_type to use with this domain association. This attribute can only be used with vmmDomain domain association.
```suggestion
    - Which binding_type to use with this domain association. This attribute can only be used with VMM domain associations.
```

2024-02-27 22:12 UTC, lhercot commented on plugins/modules/mso_schema_site_anp_epg_domain.py
> +    - Which binding_type to use with this domain association. This attribute can only be used with vmmDomain domain association.
Same for all others

2024-02-27 22:12 UTC, lhercot commented on plugins/modules/mso_schema_site_anp_epg_domain.py
> +    - Which netflow_pref to use with this domain association. This attribute can only be used with vmmDomain domain association.
Which? It is only enable/disabled so it is not really which?

2024-02-28 12:14 UTC, sajagana approved these changes
LGTM!

2024-02-28 16:44 UTC, anvitha-jain approved these changes

2024-02-28 16:52 UTC, lhercot approved these changes
LGTM

2024-02-28 16:52 UTC, merged