439 440 fabic policies l3 and physical domain
CiscoDevNet/ansible-mso pull request #472
Opened 2024-06-17 10:25 UTC by akinross

fixes #439 #440

2024-06-19 01:39 UTC, sajagana submitted a review, later dismissed
LGTM!

2024-06-20 21:40 UTC, anvitha-jain requested changes

2024-06-21 06:29 UTC, akinross commented on plugins/modules/ndo_l3_domain.py
> +  cisco.mso.ndo_l3_domain:
changed

2024-06-21 14:00 UTC, sajagana approved these changes
LGTM!

2024-06-21 15:53 UTC, anvitha-jain approved these changes
LGTM

2024-06-26 14:55 UTC, sajagana approved these changes
LGTM!

2024-06-27 19:02 UTC, anvitha-jain approved these changes

2024-07-02 02:10 UTC, samiib requested changes
I had a comment from the previous PR that hasn't merged yet. Not sure if you want to fix it here or in the original PR. 😵

2024-07-02 02:10 UTC, samiib commented on plugins/modules/ndo_vlan_pool.py
> +      from_vlan:
Looks like the same change from here. https://github.com/CiscoDevNet/ansible-mso/pull/471#discussion_r1661719198

2024-07-02 13:17 UTC, samiib approved these changes
LGTM

2024-07-05 13:29 UTC, sajagana approved these changes
LGTM!

2024-07-06 01:07 UTC, samiib approved these changes
LGTM

2024-07-06 14:46 UTC, lhercot approved these changes
LGTM

2024-07-06 14:46 UTC, merged