[minor_change] Add support vrf ref as apic dn for mso_schema_site_bd_…
CiscoDevNet/ansible-mso pull request #499
Opened 2024-07-24 14:16 UTC by akinross

…l3out

fixes #497

2024-07-30 15:16 UTC, sajagana submitted a review, later dismissed
LGTM!

2024-07-31 11:14 UTC, samiib requested changes

2024-07-31 11:20 UTC, akinross commented on plugins/modules/mso_schema_site_bd_l3out.py
> +        if l3out.get("tenant") and (l3out.get("schema") or l3out.get("template")):
How would this work when it is inside the l3out dict?

2024-07-31 12:32 UTC, samiib commented on plugins/modules/mso_schema_site_bd_l3out.py
> +        if l3out.get("tenant") and (l3out.get("schema") or l3out.get("template")):
Hmm true I thought there would be a reason. 
However, based on the documentation (although not super clear) it appears to be possible.
Could `mutually_exclusive` be added to the l3out dictionary spec on line 176?

2024-07-31 12:57 UTC, sajagana approved these changes
LGTM!

2024-07-31 12:59 UTC, samiib approved these changes
LGTM!

2024-07-31 17:48 UTC, gmicol approved these changes
LGTM

2024-08-01 18:09 UTC, anvitha-jain approved these changes

2024-08-02 16:01 UTC, shrsr approved these changes
LGTM

2024-08-06 02:29 UTC, lhercot approved these changes
LGTM

2024-08-06 02:29 UTC, merged