[minor_change] Add support for name attribute in mso_schema_template_external_epg_subnet module (DCNE-59)
CiscoDevNet/ansible-mso pull request #559
Opened 2024-10-29 13:10 UTC by akinross

fixes #512

2024-10-30 10:27 UTC, lhercot requested changes

2024-10-30 10:27 UTC, lhercot commented on tests/integration/targets/mso_schema_template_external_epg_subnet/tasks/main.yml
>      - add_epg_subnet_no_ag.msg == "MSO Error 400{{':'}} ExternalEPG{{':'}} ansible_test_1 in Schema{{':'}} ansible_test , Template{{':'}} Template1 External EPG validation error{{':'}} aggregate shou
Update task title to reflec the additional <4.3 limit

2024-10-30 11:38 UTC, lhercot approved these changes
LGTM

2024-10-30 17:55 UTC, shrsr approved these changes
LGTM

2024-10-31 16:11 UTC, gmicol approved these changes
LGTM

2024-11-04 01:03 UTC, samiib approved these changes
LGTM

2024-11-11 03:32 UTC, merged